import puppeteer from "puppeteer-core";
const b = await puppeteer.launch({ executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", headless: "new", args: ["--no-sandbox","--use-angle=swiftshader","--enable-unsafe-swiftshader","--window-size=1920,1080"] });
const p = await b.newPage();
p.on("console", (m) => { if (m.type() === "error" || m.text().includes("[sphere]")) console.log("CONSOLE:", m.type(), m.text().slice(0,300)); });
p.on("pageerror", (e) => console.log("PAGEERROR:", String(e).slice(0,300)));
await p.setViewport({ width: 1920, height: 1080 });
await p.goto("http://127.0.0.1:3000/", { waitUntil: "networkidle0", timeout: 60000 });
await new Promise((r) => setTimeout(r, 6000));
await b.close();
console.log("ERRCHECK_DONE");
